config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/about'

  root 'welcome#index'
  resources :registeredapps

  namespace :api, defaults: { format: :json } do
  	match '/events', to: 'events#preflight', via: [:options]
  	resources :events, only: [:create]
 end
  devise_for :users, controllers: { confirmations: 'confirmations' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :registeredapp
end

app/models/registeredapp.rb
class Registeredapp < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :registeredapps
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
	skip_before_action :verify_authenticity_token
 	before_action :set_access_control_headers
 	def set_access_control_headers
		headers['Access-Control-Allow-Origin'] = '*'
		headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
		headers['Access-Control-Allow-Headers'] = 'Content-Type'
	end
 	def create
		@registered_application = Registeredapp.find_by(url: request.env['HTTP_ORIGIN'])
		unless @registered_application.present?
			render json: "Unregistered application", status: :unprocessable_entity
		end
 		@event = @registered_application.events.new(event_params)
		if @event.save
			render json: @event, status: :created
		else
			render json: {errors: @event.errors}, status: :unprocessable_entity
		end
	end
 	def preflight
		head 200
	end
 	private
	def event_params
		params.require(:event).permit(:name)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    your_new_after_confirmation_path
  end
end

app/controllers/registeredapps_controller.rb
class RegisteredappsController < ApplicationController
  def create
    @registeredapp = Registeredapp.new
    @registeredapp.name = params[:registeredapp][:name]
    @registeredapp.url = params[:registeredapp][:url]
    @registeredapp.user = current_user
     if @registeredapp.save
      flash[:notice] = "You successfully registered your app."
      redirect_to @registeredapp
    else
      flash.now[:alert] = "There was an error registering your app. Please try again."
      render :new
    end
  end
   def new
    @registeredapp = Registeredapp.new
  end
   def show
    @registeredapp = Registeredapp.find(params[:id])
    @events = @registered_application.events.group_by(&:name)
    unless @registeredapp.user == current_user
      flash[:alert] = "You are not authorized to view this app."
      redirect_to root_path
    end
  end
   def index
    @registeredapps = []
    @allapps = Registeredapp.all
    @allapps.each do |app|
      if app.user == current_user
        @registeredapps << app
      end
    end
  end
   def edit
    @registeredapp = Registeredapp.find(params[:id])
  end
   def update
    @registeredapp = Registeredapp.find(params[:id])
    @registeredapp.name = params[:registeredapp][:name]
    @registeredapp.url = params[:registeredapp][:url]
     if @registeredapp.save
      flash[:notice] = "Registered app was updated successfully."
      redirect_to @registeredapp
    else
      flash.now[:alert] = "There was an error updating the registered app. Please try again."
      render :edit
    end
  end
   def destroy
    @registeredapp = Registeredapp.find(params[:id])
    if @registeredapp.destroy
      flash[:notice] = "\"#{@registeredapp.name}\" was deleted successfully."
      redirect_to registeredapps_path
    else
      flash.now[:alert] = "There was an error deleting the app. Try again?"
      render :show
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
    <div class='inner-wrapper'>
       <ul class='nav nav-tabs'>
        <li class='blocmetrics-logo' ><%= link_to 'Blocmetrics', root_url %></li>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", welcome_about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "My Apps", registeredapps_path %></li>
        <% end %>
        <div class='user-info pull-right'>
          <% if user_signed_in? %>
           Signed in as: <strong><%= current_user.email %></strong> |
           <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
           <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
           <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>
      </ul>
    </div>
  </div>
  <div class='container'>
    <div class='inner-wrapper'>
      <% if flash[:notice] %>
          <div class='alert alert-success'>
            <button type='button' class='close' data-dismiss='alert'>&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:error] %>
          <div class='alert alert-danger'>
            <button type='button' class='close' data-dismiss='alert'>&times;</button>
            <%= flash[:error] %>
          </div>
        <% elsif flash[:alert] %>
          <div class='alert alert-warning'>
            <button type='button' class='close' data-dismiss='alert'>&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
      <%= yield %>
    </div>
  </div>
  <div class='container footer'>
    <div class='inner-wrapper'>
      <footer>(FOOTER) Blocmetrics. BLOC.io</footer>
    </div>
  </div>
  </body>
</html>

app/views/registeredapps/edit.html.erb
<h1>Edit Your Registered App</h1>
<div class="row">
	<div class="col-md-8">
		<%= form_for @registeredapp do |f| %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control', placeholder: "Enter the site's name here" %>
			</div>
			<div class="form-group">
				<%= f.label :URL %>
				<%= f.text_field :url, class: 'form-control', placeholder: "Enter the site's URL here" %>
			</div>
			<div class="form-group">
				<%= f.submit "Save", class: 'btn btn-success' %>
			</div>
		<% end %>
	</div>
</div>

app/views/registeredapps/index.html.erb
<h1>My Registered Apps</h1>
 <div class="row">
	<div class="col-md-8">
		<% if current_user.registeredapps.any? %>
			<% @registeredapps.each do |app| %>
				<div class="media">
					<div class="media-body">
						<h4 class="media-heading">
							<%= link_to app.name, app %>
						</h4>
					</div>
				</div>
			<% end %>
		<% else %>
			<p>You haven't registered any apps yet.</p>
		<% end %>
	</div>
	<div class="col-md-4", style="padding-top:10px;">
		<%= link_to "Register a new app", new_registeredapp_path, class: 'btn btn-success' %>
	</div>
</div> 

app/views/registeredapps/new.html.erb
<h1>New App Registration</h1>
 <div class="row">
	<div class="col-md-8">
		<%= form_for @registeredapp do |f| %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control', placeholder: "Enter the site's name here" %>
			</div>
			<div class="form-group">
				<%= f.label :url %>
			<%= f.text_field :url, class: 'form-control', placeholder: "Enter the site's URL here" %>
			</div>
			<div class="form-group">
				<%= f.submit "Save", class: 'btn btn-success' %>
			</div>
		<% end %>
	</div>
</div>

app/views/registeredapps/show.html.erb
<%= javascript_include_tag "https://www.google.com/jsapi" %>

<h1><%= @registeredapp.name %></h1>
 <div class="row">
	<div class="col-md-8">
		<h4>URL: <%= link_to @registeredapp.url, "#{@registeredapp.url}" %></h4>
			<%= pie_chart @registered_application.events.group(:name).count %>
      <%= line_chart @events.group_by_day(:created_at).count %>
		<p style="font-size:14px;"><%= @events.count %> events exist for this app</p>
		<p style="font-size:12px;">Added by <%= @registeredapp.user.email %></p>
	</div>
	<div class="col-md-4">
		<%= link_to "Edit", edit_registeredapp_path, class: 'btn btn-success' %>
		<%= link_to "Delete", [@registeredapp], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this app from Blocmetrics?'} %>
	</div>
</div>